version: 2.1

executors:
  ask-executor:
    docker:
      - image: xavidop/alexa-ask-aws-cli:2.0

jobs:
  checkout:
    executor: ask-executor
    steps:
      - checkout
      - run: chmod +x -R ./scripts
      - persist_to_workspace:
          root: /home/node/
          paths:
            - project
  create_hosted_skill:
    executor: ask-executor
    steps:
      - attach_workspace:
          at: /home/node/
      - run: 
          name: create hosted skill
          command: |
            basename=$(basename $GIT_TEMPLATE_URL)
            repo_folder=${basename%.*} 
            ./create_hosted_skill.sh $repo_folder
      - persist_to_workspace:
          root: /home/node/
          paths:
            - project
  download_template:
    executor: ask-executor
    steps:
      - attach_workspace:
          at: /home/node/
      #removing ask cli template lambda + skill-packages
      - run: rm -rf template/lambda/
      - run: rm -rf template/skill-package/interactionModels
      - run: git clone $GIT_TEMPLATE_URL
       #cleanup template downloaded metada, getting only lambda + skill-packages objeects 
       #copy downloaded template fully cleaned to final template to push
      - run: 
          name: clean up donwloaded template
          command: |
            basename=$(basename  $GIT_TEMPLATE_URL)
            repo_folder=${basename%.*} 
            rm -rf $repo_folder/.git && rm -rf $repo_folder/.ask && rm -rf $repo_folder/ask-resources.json && rm -rf $repo_folder/skill-package/skill.json 
            cp -R $repo_folder/. template/
      - persist_to_workspace:
          root: /home/node/
          paths:
            - project
  deploy_hosted_skill:
    executor: ask-executor
    steps:
      - attach_workspace:
          at: /home/node/
      #init some git global variables
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"
      #push the final skill
      - run: cd template/ && git add . && git commit -m "template added" && git push origin master
      - persist_to_workspace:
          root: /home/node/
          paths:
            - project
workflows:
    skill-pipeline:
      jobs:
        - checkout
        - create_hosted_skill:
            requires:
              - checkout
        - download_template:
           requires:
            - create_hosted_skill
        - deploy_hosted_skill:
           requires:
            - download_template
