version: 2.1

executors:
  ask-executor:
    docker:
      - image: xavidop/alexa-ask-aws-cli:2.0

jobs:
  checkout:
    executor: ask-executor
    steps:
      - checkout
      - run: chmod +x -R ./scripts
      - persist_to_workspace:
          root: /home/node/
          paths:
            - project
  create:
    executor: ask-executor
    steps:
      - attach_workspace:
          at: /home/node/
      - run: cd scripts/ && ./create_hosted_skill.sh
      - persist_to_workspace:
          root: /home/node/
          paths:
            - project
workflows:
    skill-pipeline:
      jobs:
        - checkout
        - create:
            requires:
              - checkout
